---
version: 2
updates:
  - package-ecosystem: terraform
    directory: /infra
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - github-actions
